version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react-frontend
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379" 